name: CI Vaultify Workflow

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md' # Ignore changes in markdown files only
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md' # Ignore changes in markdown files only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: main
          path: './'

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Go Tests
        run: go test -v ./tests -coverprofile=coverage.out
        continue-on-error: false

      - name: Check for Test Failures
        if: failure()
        run: echo "Tests failed. Check the logs for more details."
  
      - name: Test Coverage
        run: go tool cover -func=coverage.out
        continue-on-error: false