name: Validate Vaultify CLI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4  # Use the Go version you need

      - name: Install dependencies
        run: go mod download

      - name: Build Vaultify CLI
        run: go build -o vaultify