name: CI Vaultify Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          path: './'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4  # Use the Go version you need

      - name: Build Vaultify CLI
        run: go test -v ../tests -cover